### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by MateiGamingYTB** [ILOVEMCPE/ILOVEMCPECore#1]
ToDo list for this plugin...
Translate to Romanian
Prefix ILOVEMCPE
AND MORE...

Can help me please with this plugin?
How i create a folder in this resposity???
I don't now how to create a folder....
Can help me to unarhive the ZIP and upload normal files and folders in the ZIP in the resposity? I don't now how do this in android.....I do't have any PC...

**Comment by EpicSteve33** [comment]
Hello

**Comment by MateiGamingYTB** [comment]
Hello

**Comment by EpicSteve33** [comment]
is this your core plugin???

**Comment by EpicSteve33** [comment]
@MateiGamingYTB who's plugin is this

**Comment by jasonwynn10** [comment]
1. Why is the only file here a zip?
2. What is the plugin's purpose
3. Why are you trying to develop a plugin without a PC?

**Comment by remotevase** [comment]
Hello... Whose plugin is this? What is it for? Why are you doing this on mobile? What are we supposed to do? Are you able to code??!

**Comment by jasonwynn10** [comment]
@remotevase I think that we were just thrown in here at random to do something

**Comment by remotevase** [comment]
Quite likely, but I will do ABSOLUTELY NOTHING if the owner is unable to code anything **on his own**

**Comment by EpicSteve33** [comment]
@jasonwynn10 @remotevase I do not believe this belongs to him I think he may have stolen this core from somewhere

**Comment by remotevase** [comment]
Quite likely

**Comment by remotevase** [comment]
Actually, definitely. It says in README

> A ILOVEMCPE Servers Core, it is translated and copied from Minetox

**Comment by EpicSteve33** [comment]
I will not help on a project with stolen code unless it's my own project xD

**Comment by remotevase** [comment]
XD Nor will I

**Comment by jasonwynn10** [comment]
agreed

**Comment by majovec** [comment]
@CreeperFace01 mas tu hračky

**Comment by MateiGamingYTB** [comment]
Ok, don't help to continue a stolen code, but help me to make a new core for my ILOVEMCPE Server please

**Comment by remotevase** [comment]
First, I want to see you do some coding yourself, and once I have ensured that you posess the ability to code, then I will help.

**Comment by Creeperface01** [comment]
Yes its main.

**Comment by MateiGamingYTB** [comment]
I don't now how to coding i now to configure into plugin (languace, prefix, etc) i m into à 8 à class into school and my teacher is bad and does not want to teach me to encode PHP

**Comment by MateiGamingYTB** [comment]
If you do not want to help me when I do my plugin, help me to solve errors of this plugin
Sorry for my bad English, i m Romanian

**Comment by MateiGamingYTB** [comment]
@jasonwynn10  i don't now how unarchive the zip and upload unziped archhive,(I NOW HOW UNZIP, BUT IN DON'T NOW HOW UPLOAD UNZIPED ARCHIVE TO RESPO ON ANDROID) i dont have a PC....

**Comment by remotevase** [comment]
I will not aid you in this plugin since you are unable to code it yourself, neither will @jasonwynn10 or @EpicSteve33
